input {
  file {
    path => "/opt/Digital_Footprint_System/result/domains-monitor/jsonl/*.jsonl"
    start_position => "beginning"
    sincedb_path => "/var/lib/logstash/plugins/inputs/file/domains-monitor.sincedb"
    mode => "read"
    exit_after_read => true
    codec => json
  }
}

filter {
  fingerprint {
    source => ["find_domain", "api_item", "domain"]
    target => "[@metadata][doc_id]"
    method => "SHA256"
  }

  if [find_domain] {
    mutate {
      copy => { "find_domain" => "[@metadata][safe_find_domain]" }
      lowercase => [ "[@metadata][safe_find_domain]" ]
      gsub => [
        "[@metadata][safe_find_domain]", "[\\s]+", "-",
        "[@metadata][safe_find_domain]", "[^a-z0-9._-]", "-"
      ]
      add_field => {
        "[@metadata][target_index]" => "domains-monitor-%{[@metadata][safe_find_domain]}"
      }
    }
  } else {
    mutate {
      add_field => {
        "[@metadata][target_index]" => "domains-monitor-unknown"
      }
    }
  }

  ruby {
    code => 'event.set("@timestamp", LogStash::Timestamp.now)'
  }
}

output {
  elasticsearch {
    hosts => ["https://192.168.150.128:9200"]
    index => "%{[@metadata][target_index]}"
    user => "elastic"
    password => "qwerty"
    ssl_verification_mode => "none"
    document_id => "%{[@metadata][doc_id]}"
  }

  stdout {
    codec => rubydebug
  }
}
