input {
  file {
    path => "/opt/Digital_Footprint_System/result/github-monitor/jsonl/*.jsonl"
    start_position => "beginning"
    sincedb_path => "/var/lib/logstash/plugins/inputs/file/github-monitor.sincedb"
    mode => "read"
    codec => json
  }
}

filter {
  mutate {
    rename => {
      "Ссылка" => "url"
      "Наименование репозитория" => "repository_name"
    }
  }

  if [find_domain] {
    mutate {
      add_field => {
        "domain_zone" => "%{[find_domain]}"
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["https://192.168.150.128:9200"]
    index => "github-monitor-%{[find_domain]}"
    user => "elastic"
    password => "qwerty"
    ssl_verification_mode => "none"
  }

  stdout {
    codec => rubydebug
  }
}
