input {
  file {
    path => [
      "/opt/Digital_Footprint_System/result/infosearch/jsonl/*.jsonl"
    ]
    start_position => "beginning"
    sincedb_path => "/var/lib/logstash/plugins/inputs/file/infosearch.sincedb"
    mode => "read"
    exit_after_read => true
    codec => plain {
      charset => "UTF-8"
    }
  }
}

filter {
  json {
    source => "message"
  }

  mutate {
    remove_field => ["message", "host", "path", "@version"]
  }

  if [domain_zone] {
    mutate {
      add_field => {
        "[@metadata][target_index]" => "infosearch-%{[domain_zone]}"
      }
    }
  } else {
    mutate {
      add_field => {
        "[@metadata][target_index]" => "infosearch-unknown"
      }
    }
  }
}

output {
  stdout {
    codec => rubydebug
  }

  elasticsearch {
    hosts => ["https://192.168.150.128:9200"]
    index => "%{[@metadata][target_index]}"
    user => "elastic"
    password => "qwerty"
    ssl_verification_mode => "none"
  }
}
