input {
  file {
    path => "/opt/Digital_Footprint_System/result/leakcheck/jsonl/*_leaks_new.jsonl"
    start_position => "beginning"
    sincedb_path => "/var/lib/logstash/plugins/inputs/file/leakcheck.sincedb"
    mode => "read"
    exit_after_read => true
    codec => json
  }
}

filter {
  mutate {
    lowercase => ["domains"]
  }

  mutate {
    gsub => [
      "domains", "\\.", "-",
      "domains", "[^a-z0-9_-]", "-"
    ]
  }

  if [domains] and [domains] != "" {
    mutate {
      add_field => {
        "[@metadata][target_index]" => "leaksearch-domains-%{[domains]}"
      }
    }
  } else {
    mutate {
      add_field => {
        "[@metadata][target_index]" => "leaksearch-domains-unknown"
      }
    }
  }

  fingerprint {
    source => ["domains", "source", "email", "year"]
    target => "[@metadata][doc_id]"
    method => "SHA256"
  }
}

output {
  elasticsearch {
    hosts => ["https://192.168.150.128:9200"]
    index => "%{[@metadata][target_index]}"
    user => "elastic"
    password => "qwerty"
    ssl_verification_mode => "none"
    }

  stdout {
    codec => rubydebug
  }
}
